"""
Initially generated by ChatGPT

Prompt: Write a Python script that uses the Strava API to download a given user’s activity data

ChatGPT: 

✅ Requirements
First, install required packages:

```bash
pip install requests
```

🔐 Step 1: Get Access Token (OAuth2.0 Flow)
You need to perform a one-time step to get a refresh token by authenticating your app with a browser redirect. Here’s the URL to generate an access code:

```bash
https://www.strava.com/oauth/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=http://localhost&approval_prompt=force&scope=activity:read_all
After approving access, you'll get a code like ?code=AUTH_CODE in the URL.
```

🐍 Step 2: Python Script
(follows)

📁 Output
The script will create a file strava_activities.json with your activity data.
You can parse this JSON to extract fields like distance, moving_time, type, start_date, etc.
"""

import requests
import json
import time

# Replace with your actual values
from _settings.secrets import CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN

def get_access_token():
    response = requests.post(
        'https://www.strava.com/oauth/token',
        data={
            'client_id': CLIENT_ID,
            'client_secret': CLIENT_SECRET,
            'grant_type': 'refresh_token',
            'refresh_token': REFRESH_TOKEN
        }
    )
    response.raise_for_status()
    return response.json()['access_token']

def get_activities(access_token, per_page=30, max_pages=5):
    headers = {'Authorization': f'Bearer {access_token}'}
    activities = []
    page = 1

    while page <= max_pages:
        url = f'https://www.strava.com/api/v3/athlete/activities?per_page={per_page}&page={page}'
        res = requests.get(url, headers=headers)
        res.raise_for_status()
        data = res.json()
        if not data:
            break
        activities.extend(data)
        page += 1
        time.sleep(1)  # Be polite to the API

    return activities

def main():
    token = get_access_token()
    activities = get_activities(token)
    
    # Save to file
    with open('strava_activities.json', 'w') as f:
        json.dump(activities, f, indent=2)
    
    print(f"Downloaded {len(activities)} activities.")

if __name__ == '__main__':
    main()

